### ISSUE TITLE
What to call things

### ISSUE THREAD

**Issue by mcabbott** [mcabbott/AxisRanges.jl#3]
This package isn't registered yet, partly because what to call things is unclear. Thoughts:

1. Julia has adopted `index::Int ∈ axes(A,1)`. So I think these other structures need other names. 

2. From NamedDims.jl, each `name::Symbol` belongs to a dimension, `d ∈ 1:ndims(A)`, which is fine. It uses `dimnames(A)` to give the list now, not `Base.names(A)`.

3. A `value` is what `A[1,2]` returns, this is what `setindex!` calls it.

3. LabelledArrays.jl attaches a `label::Symbol` to every element of the array, 
  so that perhaps `A.label == A[2,2]`. 

4. For now I use `key` for the thing you lookup. But `Base.keys(A)` appears to be another way of saying `CartesianIndices(A)`. 

But what's a vector of keys called? For now I use `ranges(A,1)`. But these do not have to be like `Base.range`'s `AbstractRange`s. Perhaps `scales(A,1)`? A scale of keys? `domains(A,1)`? Or `axiskeys(A, 1)` since they are labels along each axis, not in the bulk?

The package could then be  `AxisScales` (hard to say) or `LabelledDims` (how many `l`s again?)
or `AxisKeys` (short!) or `ScaledDims` (but not just re-scaling) or what?

**Comment by Tokazama** [comment]
I have an alternate proposal if you're interested. What if you took AxisIndices as a dependency and I transferred the pretty printing I've been working on here. I could make the default syntax the same as what you've already implemented. So it wouldn't change anything. I could change the key look up behavior to use the round brackets but include my filtering syntax as something that can be used for keys and indices. That would make this a sort of meta package binding all related packed together in a way that is more convenient for users (eg includes plotting, aliases for constructors, etc.) and sustain a modular design to the underlying components. Just an offer if you're interested.

**Comment by mcabbott** [comment]
I like the idea of collaboration, but am not clear on what is gained by some meta-package. I got a bit carried away with pretty-printing here, but the result seems good I think. What this does need, and perhaps you have already done somewhere, is tidier `findfirst(::Fix2, ::AbstractRange)` methods... is there anything like this in StaticRanges or somewhere?

**Comment by Tokazama** [comment]
Right now I use `find_first`, `find_all`, etc. to get better performance on these. This has allowed me to optimize it in as many ways as I want without worrying about type piracy.

I'm trying to get more of the pretty printing stuff to use PrettyTables so that it's not as much of a burden to maintain. I think that's one of the things that killed AxisArrays, trying to do too much without people interested in maintaining each aspect of it.
